added a state to calculator
Spayco/react-calculator pull request #7
Opened 2020-10-01 14:12 UTC by Spayco

in this branch, I added the state to the `App` component to update the display through the `buttons`.

2020-10-01 19:22 UTC, Forison requested changes
## Status:: Change required❌
# 🙋‍♂️ @Spayco 
#### You have done a good job on this one so far, here are a few issues we have to address to get the project approved🤗.
* [ ] The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- Kindly make sure the image in the readme is visible to visitors. (Kindly check the image path).
* [ ] Kindly address the issue with the implementation of `%`, currently it is not functioning as required.
- onClick `50` followed by click `%` the result should be 0.5.
- onClick `50` followed by `-`, `30`click `%` the result should be 0.2.
* [ ] display field overflows when the digit is long, kindly address it. 
![overflo](https://user-images.githubusercontent.com/29695661/94853025-c06be000-03f8-11eb-80de-d0e95c5e2829.png)
- Check my comment below👇.
### That is it, kindly make the change and submit a re-review👨‍🔧.
#### Happy coding👨‍🔧
Addo Forison

2020-10-01 19:22 UTC, Forison commented on src/components/Button.js
> +/* eslint-disable react/button-has-type */
* [ ] Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))
- Do not make change to linter configs else you miss the main learning objective in relation to the rule.

2020-10-01 19:22 UTC, Forison commented on src/components/Button.js
>  // eslint-disable-next-line react/prefer-stateless-function
- Do not make any changes in config files

2020-10-01 19:22 UTC, Forison commented on src/components/ButtonPanel.js
>  // eslint-disable-next-line  react/prefer-stateless-function
- Do not make any changes in config files

2020-10-02 16:23 UTC, bellom approved these changes
## Hi @Spayco  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-10-02 17:39 UTC, merged